### ISSUE TITLE
How to use your addon to generate dungeons.

### ISSUE THREAD

**Issue by Moonteamin** [AlexeyBond/godot-constraint-solving#1]
Hi there! I've been busy messing around with your addon and trying to find a way to generate rooms that connect in a 2D Tilemap. I was going to try to mess with the rules, but am unsure how it works.
Do you know any good resources on how to use your WFCRules?

**Comment by AlexeyBond** [comment]
Hi.

There is no proper documentation on internal components of the addon yet. So best I can do now is to give some hints and recommend reading the code.

If you're going to modify rules by adding global constrains to achieve connectivity then most likely you'll have to modify or implement subclass of [WFCProblem2D](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/problems/2d/problem_wfc_2d.gd).
Most likely, you'll have to deal with following methods:

- [`compute_cell_domain`](https://github.com/AlexeyBond/godot-constraint-solving/blob/1e1213e4adb0a01ce161c8ac05398f6b6156986c/addons/wfc/problems/2d/problem_wfc_2d.gd#L64) - it calculates new domain (set of tiles that may be contained in this cell) of a cell after some of cells it depends on was updated. Domains are represented as [bit-sets](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/utils/bitset.gd) where N'th set bit means that this cell may contain N'th tile. Mapping between tile numbers (N's) and actual tiles in TileMap/Grid map is performed by [mappers](https://github.com/AlexeyBond/godot-constraint-solving/tree/master/addons/wfc/problems/2d/mappers). Note that low-level constraint solver uses single-dimensional cell indexes (mostly for performance reasons, copying 2+d arrays would be expensive) and WFCProblem2D maps those 1d indices to and from 2d coordinates using [coord_to_id](https://github.com/AlexeyBond/godot-constraint-solving/blob/1e1213e4adb0a01ce161c8ac05398f6b6156986c/addons/wfc/problems/2d/problem_wfc_2d.gd#L39) and [id_to_coord](https://github.com/AlexeyBond/godot-constraint-solving/blob/1e1213e4adb0a01ce161c8ac05398f6b6156986c/addons/wfc/problems/2d/problem_wfc_2d.gd#L42) methods.
- [`mark_related_cells`](https://github.com/AlexeyBond/godot-constraint-solving/blob/1e1213e4adb0a01ce161c8ac05398f6b6156986c/addons/wfc/problems/2d/problem_wfc_2d.gd#L85) - it is called when domain of certain cell has changed and should mark (by calling a callbeck with their indices) other cells that depend on that cell and thus are likely to have their domains changed.
- [`get_dependencies_range`](https://github.com/AlexeyBond/godot-constraint-solving/blob/1e1213e4adb0a01ce161c8ac05398f6b6156986c/addons/wfc/problems/2d/problem_wfc_2d.gd#L114C6-L114C28) - returns a half-size of a rect that contains all cells that depend on a cell in the center of a rect. It is used to determine a proper way to split a problem into smaller problems that can be solved concurrently. It's most likely to be infinite (`Vector2i(INT_MAX, INT_MAX)`) in case of a problem with global constraints - so no concurrent solving will be possible.

Theoretically, it should be possible to implement global constraints by modifying/overriding the methods mentioned above. However, that's far from being trivial.

---

But, I can suggest an easier approach to your problem:

First you can generate a skeleton of the dungeon using a different algorithm. A skeleton should include minimal road built of passable cells and minimal set of walls separating different rooms. E.g.:

![image](https://github.com/AlexeyBond/godot-constraint-solving/assets/7383049/14e94b7e-53a7-4f21-91ae-a2f8b8af6858)

Note there are huge gaps between road and walls. They are necessary 'cause otherwise WFC will not be able to genereate the map without contradictions. Necessary minimal size of gaps may depend on value returned by previously mentioned `get_dependencies_range` method, which in turn depends on the tileset and set of rules.

Then you can let WFC fill the gaps:

![image](https://github.com/AlexeyBond/godot-constraint-solving/assets/7383049/8a666f9b-cb5f-45ac-b885-efdfb2138437)

This approach will be *much* easier to implement and it doesn't stop solver from generating large enough maps concurrently. But it may generate some unconnected rooms (which may be avoided by adding some rules to negative sample map to forbid generation of new walls):

![image](https://github.com/AlexeyBond/godot-constraint-solving/assets/7383049/4847ac0a-fb77-4c19-b82f-df0220451bb9)

![image](https://github.com/AlexeyBond/godot-constraint-solving/assets/7383049/e2259a03-ea6a-44ee-b653-9ce44ee4ce42)

**Comment by AlexeyBond** [comment]
In version [1.2](https://github.com/AlexeyBond/godot-constraint-solving/releases/tag/1.2) an API for itegration of other algorithms to generate initial constraints is added. Implementation of a dungeon generator is also included there. See an [example](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/examples/demo_wfc_2d_tilemap_dungeon.tscn).

**Comment by Moonteamin** [comment]
> In version [1.2](https://github.com/AlexeyBond/godot-constraint-solving/releases/tag/1.2) an API for itegration of other algorithms to generate initial constraints is added. Implementation of a dungeon generator is also included there. See an [example](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/examples/demo_wfc_2d_tilemap_dungeon.tscn).

Thank you for the help!
