### ISSUE TITLE
Rerun on different Rect. 

### ISSUE THREAD

**Issue by Buyancy** [AlexeyBond/godot-constraint-solving#13]
Hello. Again not an issue, but just want to ask/discuss the plugin. 

I am trying to dynamically load chunks of the world as the camera moves around. Basically the algorithm would basically just load the tiles in the world that are visible on the camera. Is there an easy way to rerun the WFC algorithm on a different Rect2i on the same TileMap? 

Thanks!

**Comment by AlexeyBond** [comment]
Hi.

If you do already have a way to choose next rect to run the algorithm on, then it should be easy:
- call [`reset`](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/nodes/generator_2d.gd#L263) method on generator node
- set the new rect using [`rect`](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/nodes/generator_2d.gd#L14)
- call [`start`](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/nodes/generator_2d.gd#L163) to start generator again

Just don't do it before generator finishes with previous job (it emits [`done`](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/nodes/generator_2d.gd#L95) signal when it does).

Some caveats are:
- new rects should overlap adjacent generated areas by at least one cell. Otherwise content of the new rect will not be consistent with them.
- this won't work with preconditions like a dungeon generator out of the box - it would generate a separate dungeon in every rect.

---

A more generic solution for dynamic generation is currently on todo list. It may be useful if you will share some of your experience in case of succes.
