### ISSUE TITLE
Big key dungeons

### ISSUE THREAD

**Issue by dwidge** [AlexeyBond/godot-constraint-solving#15]
Hello, to make a lock and key dungeon:

Generate your dungeon with the locked doors.
- Put keys in the rooms directly behind these locked doors.
- Move every key (at least) one room towards the entrance.
- This should yield a dungeon that's always solvable (every room can be reached no matter what).
https://www.reddit.com/r/proceduralgeneration/comments/1oceim/anyone_know_a_guarenteedsolvable_small_key/

How to make a series of separate walkable regions with wfc? And maybe also ensure that there is somewhere a certain tile (door) between each A -> A+1 region. And maybe a way to find the door of each region, so a key can be generated and linked to it.

**Comment by AlexeyBond** [comment]
Hi. Generating global structures, like connected passable regions or series of such, with WFC alone isn't trivial and currently isn't supported in this plugin.

Instead, this addon allows to run another algorithm (called *precondition*, because it sets initial conditions for WFC) before running WFC to limit what tiles are allowed in what cells. Such algorithm may generate a global structure, like [WFC2DPreconditionDungeon](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/problems/2d/preconditions/precondition_2d_dungeon.gd) does. And after that WFC will consistently fill it with concrete tiles.
