### ISSUE TITLE
Assertation Failed Not BT

### ISSUE THREAD

**Issue by TizWarp** [AlexeyBond/godot-constraint-solving#18]
I'm just trying to mess around with the dungeon generator and I can't seem to figure out what I am doing wrong.

I have a wfc_generator node setup correctly that works normally but if I ad a dungeon precondition I get assertion failed (not bt)

I have very closely studied to example and even deleted and recreated the wfc_generator node inside the example and cannot reproduce this error. 

I assume I am doing something wrong with tile maps as that is the only difference between the example and my scene at this point.

**Comment by AlexeyBond** [comment]
Hi.

This error means that the precondition has returned an empty domain for certain cell.
I.e. it says "I don't know any tile that can be placed here".

If dungeon precondition is the only precondition set up, this is most likely because it could not find any wall tiles.
Try using [this revision of addons/wfc/problems/2d/preconditions/precondition_2d_dungeon.gd](https://github.com/AlexeyBond/godot-constraint-solving/blob/b16f8a86b86653e463e834512a311772303a7fdd/addons/wfc/problems/2d/preconditions/precondition_2d_dungeon.gd).
If that's the issue, a different assertion (with more meaningful message) will fail.

It also can be an interference between multiple preconditions or between precondition and edge condition, if you do specify one.
