### ISSUE TITLE
[Suggestion] Multi-Layered TileMap Support

### ISSUE THREAD

**Issue by ryzech** [AlexeyBond/godot-constraint-solving#2]
I see according to the features implementation it is not yet added. Is there any known workarounds or any current plans to add it to this plugin? If i want to add trees on top of tiles already placed, with the current features this is not possible (see image below.)

Positive Rule Map
![image](https://github.com/AlexeyBond/godot-constraint-solving/assets/61711965/ae80a15c-917d-4e12-9165-a6cf3fcfbd05)

Generated Output
![image](https://github.com/AlexeyBond/godot-constraint-solving/assets/61711965/99ecb01b-7f56-445b-9142-df1e28b7d7a1)

**Comment by AlexeyBond** [comment]
Hi.

I did think about adding such feature. I can see two possible approaches to implement it:
1. Implement 3D WFC support and treat layer index as Z coordinate. That's why multi-layer tilemaps are mentioned along with 3D support in readme.
2. Implement a [2D mapper](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/problems/2d/mappers/mapper_2d.gd) that works with multiple layers and treats each combination of tiles on different layers as a single tile. This approach is easier and may work even better in many cases - e.g. it will work well when different layers use different tilesets.

I will implement both approaches sooner or rather later. But right now I'm busy with different feature plus some more fundamental issues of this addon.

The approach with multi-layer 2D mapper seems easy enough, so you (or anybody else) are welcome to implement it and submit a PR.

**Comment by Supamiu** [comment]
Hi @AlexeyBond, do you have more guidance on that second approach? I need something similar for my project and better not reinvent the wheel, I just need to check if this WFC implementation can handle pre-placed tiles (like place main goals in the map first, then make WFC populate the map) and then I'd be happy to give multi-layers a try if you don't have time for it.

**Comment by AlexeyBond** [comment]
@Supamiu

Hi.

That approach requires implementation of a new [mapper](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/problems/2d/mappers/mapper_2d.gd) class.

A mapper maps tiles (in format depending on specific map node type) to and from integers, which are used by the algorithm. So the algorithm works with a map node as with something like a 2D array of integers. A single-layer mapper uses only one layer e.g. `tile A <=> 0, tile B <=> 1, ...`. In case of multi-layer mapper, it should map between combinations of tiles on different layers and numbers e.g. `(tile X on layer 0, tile Y on layer 1, no tile on layer 2 and tile Z on layer 3) <=> 0, (tile X on layer 0, tile Y on layer 1, tile W on layer 2, tile U on layer 3) <=> 1, ...`. The numbers must start with 0, and go on sequentially, without unused numbers between used numbers.

One tile on a layer can be represented as vector of 4 integers (see [`_read_cell_attrs` in `WFCTileMapMapper2D`](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/problems/2d/mappers/mapper_2d_tilemap.gd#L21) and [`write_cell` in same class](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/problems/2d/mappers/mapper_2d_tilemap.gd#L77)). A single-layer mapper uses a [dictionary](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/problems/2d/mappers/mapper_2d_tilemap.gd#L6) to efficiently map a tile vector to number and a [lazily-populated](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/problems/2d/mappers/mapper_2d_tilemap.gd#L43) [array](https://github.com/AlexeyBond/godot-constraint-solving/blob/master/addons/wfc/problems/2d/mappers/mapper_2d_tilemap.gd#L14) for reverse mapping.
Perhaps, the most significant challenge with multi-layer mapper will be to choose the right data structure to store the mappings. Arrays of vectors as a key in dictionary may be an acceptable solution here, but that wouldn't be perfect - since an array will be allocated on each cell read. And I'm not sure if array can be a key in dictionary.

If the multi-layer mapper will not be significantly less efficient than a single-layer one, then a single layer mapper can be replaced with multi-layer one.

Not sure, how helpful was that. Feel free to ask any more specific questions.

> like place main goals in the map first, then make WFC populate the map

That should work fine. However, tiles of main goals should be present in positive sample map to allow the algoritm to generate their neighbours correctly. And that means that the generator will be able to place more such tiles in different places. If it's not desired, then some additional customization of constraints will be necessary. That isn't yet fully supported in master version of the addon, but there is some work-in-progress (but mostly completed) functionality for that in [another branch](https://github.com/AlexeyBond/godot-constraint-solving/compare/preconditions).

**Comment by Supamiu** [comment]
I was thinking of two different approaches for storing, dunno which one is best yet, still trying to get a proper understanding of how mapper_2d works 😄.

These approaches are:

- Make `_read_cell_attrs` return an `Array[Vector4i]` and take one more arg that's `layers: int`, to indicate the # of layers it should scan, then store these as usual in the disctionary (and yes, anything can be a key in GDScript's Disctionnaries)
- Create a model that's called `LayeredCellInfo` that contains `x: int, y: int, tiles: Array[int], alts: Array[int]` but I'm not sure how alts are used at all so I'm not very comfortable with this level of changes (even thi this would be a different mapper anyways).

So atm I'm trying to implement the first one and I'll try to benchmark it to see how it goes 😄

**Comment by AlexeyBond** [comment]
Multi layered tilemap support (using a multi-layer mapper) is added in #4.
3D WFC is not yet implemented but I think it's still ok to close this issue.
